/**
 * Generated by pac-maker __VERSION__
 * https://github.com/Kaciras/pac-maker
 *
 * Created at: __TIME__
 */

const NO_PROXY = __NO_PROXY__;
const PROXY = __PROXY__;

// export const sources = __SOURCES__;

const rules = __RULES__;

let lastRule = "";

function FindProxyForURL(url, host) {
	for (let i = 0; i < rules.length; i++) {
		const rule = rules[i];
		if (host === rule || host.endsWith("." + lastRule)) {
			return PROXY;
		}
	}
	return NO_PROXY;
}
