/**
 * Generated by pac-maker v__VERSION__
 * https://github.com/Kaciras/pac-maker
 *
 * Created at: __TIME__
 *
 * Learn more about PAC file:
 * https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
 */

const NO_PROXY = __NO_PROXY__;
const PROXY = __PROXY__;

const rules = __RULES__;

const ruleSet = new Set();
for (const rule of rules) {
	ruleSet.add(rule);
}

function FindProxyForURL(url, host) {
	const parts = host.split(".").reverse();
	let suffix = "";

	for (let i = 0; i < rules.length; i++) {
		suffix = parts[i] + "." + suffix;
		if (ruleSet.has(suffix)) return PROXY;
	}
	return NO_PROXY;
}

// Since browser does not support export in PAC, assign variables to global instead.
globalThis.rules = rules;
