/**
 * Generated by pac-maker v__VERSION__
 * https://github.com/Kaciras/pac-maker
 *
 * Created at: __TIME__
 *
 * Learn more about PAC file:
 * https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
 */

// Since browser does not support export in PAC, assign variables to global instead.
globalThis.direct = __DIRECT__;

globalThis.proxies = __PROXIES__;

globalThis.rules = __RULES__;

function FindProxyForURL(url, host) {
	let pos = 0;

	while (pos >= 0) {
		const i = rules[host];
		if (i !== undefined) {
			return proxies[i];
		}
		pos = host.indexOf(".");
		host = host.slice(pos + 1);
	}

	return globalThis.direct;
}
